export const OK = parseInt(200)
export const CREATED = parseInt(201)
export const UNAUTHORIZED = parseInt(401)
export const FORBIDDEN = parseInt(403)
export const NOT_FOUND = parseInt(404)
export const SERVER_ERROR = parseInt(500)
export const BAD_REQUEST = parseInt(400)
